# **Optimizacion por enjambre de particulas**
**Flores Estopier Rodrigo**

Se realiza un algoritmo que nos permite optimizar la funcion de Schwefel en 4 dimensiones, la cual tiene su punto optimo en **texto en negrita**


In [1]:
import ipywidgets as widgets
from IPython import display as display
import matplotlib.pyplot as plt
import numpy as np

def create_button():
    button = widgets.Button(
        description='Next Iteration',
        disabled=False,
        button_style='',  # 'success', 'info', 'warning', 'danger' or ''
        tooltip='Next Iteration',
        icon='check'  # (FontAwesome names without the `fa-` prefix)
    )
    return button

lower_limit = -500
upper_limit = 500

n_particles = 200
n_dimensions = 4

# Función de Schwefel en 4D
def schwefel(X):
    return 418.9829 * len(X) - sum(X * np.sin(np.sqrt(np.abs(X))))

# Inicializar posiciones y velocidades de partículas
X = np.random.uniform(lower_limit, upper_limit, (n_particles, n_dimensions))  # 4 dimensiones
V = np.random.uniform(-1, 1, (n_particles, n_dimensions))


X_lbest = np.copy(X)
X_gbest = np.copy(X_lbest[0])

for I in range(n_particles):
    if schwefel(X_lbest[I]) < schwefel(X_gbest):
        X_gbest = np.copy(X_lbest[I])

# Inicializar las mejores evaluaciones de fitness
fitness_lbest = np.array([schwefel(p) for p in X_lbest])
fitness_gbest = np.min(fitness_lbest)
#print(fitness_lbest)
count = 0

def iteration(b):
    global count
    global X, X_lbest, X_gbest, V, fitness_lbest, fitness_gbest
    global lower_limit, upper_limit, n_particles, n_dimensions

    weight = 0.5
    C1 = 1.5
    C2 = 1.5

    #display.clear_output(wait=True)
    #display.display(button)
    count += 1
    print(count, "Best particle in:", X_gbest, " gbest: ", schwefel(X_gbest))

    # Actualizar velocidad y posición de las partículas
    for i in range(0, n_particles):
        r1 = np.random.rand(4)
        r2 = np.random.rand(4)
        cognitive_velocity = C1 * r1 * (X_lbest[i] - X[i])
        social_velocity = C2 * r2 * (X_gbest - X[i])
        V[i] = weight * V[i] + cognitive_velocity + social_velocity

        # Actualizar la posición
        X[i] += V[i]

        # Aplicar límites de búsqueda
        X[i] = np.clip(X[i], lower_limit, upper_limit)

        # Evaluar la nueva posición
        fitness = schwefel(X[i])

        # Actualizar la mejor posición local
        if fitness < fitness_lbest[i]:
            fitness_lbest[i] = fitness
            X_lbest[i] = X[i]

        # Actualizar la mejor posición global
        if fitness < fitness_gbest:
            fitness_gbest = fitness
            X_gbest = X[i]





# Botón para iterar
button = create_button()
button.on_click(iteration)
display.display(button)

# Información inicial
print("Initial positions:", X)


Button(description='Next Iteration', icon='check', style=ButtonStyle(), tooltip='Next Iteration')

Initial positions: [[ 1.78420648e+02 -1.38052408e+02 -4.21941941e+02  1.34359277e+02]
 [ 2.10958709e+02 -1.79505620e+02 -4.36864700e+02 -1.52263758e+02]
 [-2.36478795e+02 -1.55744584e+02  3.33686542e+02  2.20030688e+02]
 [ 1.63428130e+01  7.82293793e+01  1.29966194e+02 -8.23814841e+00]
 [ 3.29606416e+02  2.95432792e+02 -4.39028511e+01 -1.56081866e+02]
 [ 1.79484742e+02 -3.53393259e+02  4.40796551e+02 -3.75525042e+02]
 [-4.73091087e+02  4.91185565e+02  2.71703147e+02 -1.75403605e+02]
 [ 2.82615431e+02  1.99304019e+02 -1.04603166e+02 -6.46405749e+01]
 [-3.58514124e+02  4.13637336e+02 -3.45877714e+02 -1.26389518e+02]
 [-1.46522008e+02 -3.22608131e+02  1.60287750e+02 -1.10249672e+02]
 [-4.78388337e+02  4.62304658e+02 -2.21885679e+02 -4.17039485e+02]
 [-3.50873531e+02 -5.34251907e+01  8.39631295e+01  1.73706327e+02]
 [ 3.39208514e+02  2.20923702e+02 -2.68886213e+02  3.77786377e+02]
 [-2.83286229e+01  2.81934386e+01 -1.57591872e+02 -2.57310984e+02]
 [-1.96093283e+02  5.86019504e+01  1.602326

In [2]:
for i in range(500):
  iteration(None)
print(count, "Best particle in:", X_gbest, " gbest: ", schwefel(X_gbest))


1 Best particle in: [397.00641565 -97.15161969 425.92252311 164.8682633 ]  gbest:  825.532127706393
2 Best particle in: [408.45920057 -93.95770946 401.21923044 197.52169653]  gbest:  683.5771473883354
3 Best particle in: [410.71657685 -95.83079475 401.03356611 209.39374788]  gbest:  667.8259951703005
4 Best particle in: [417.33419084 -94.98198302 388.47737184 231.90275604]  gbest:  827.1540367455257
5 Best particle in: [421.48539394 397.51516596 394.94581818 201.50378346]  gbest:  366.4003441131813
6 Best particle in: [426.93087593 500.         393.15922157 191.91812264]  gbest:  931.5500870706949
7 Best particle in: [419.91590289 397.74973703 407.05911678 208.91112992]  gbest:  310.2133170238051
8 Best particle in: [421.63346591 411.42024399 410.81185634 199.06290206]  gbest:  244.3631952722651
9 Best particle in: [427.63871282 424.81539492 425.51892196 198.03168333]  gbest:  231.46526670913545
10 Best particle in: [420.49200264 409.13119188 422.71169226 438.10477589]  gbest:  54.6463