# **Algoritmo de optimizacion por colonia de hormigas**
**Flores Estopier Rodrigo**

In [13]:

import numpy as np
import random

# La primera columna ni la primera fila se utilizan
M = 2 * np.ones([11, 11])
M[1][3] = 1; M[3][5] = 1; M[5][7] = 1; M[7][9] = 1
M[9][2] = 1; M[2][4] = 1; M[4][6] = 1; M[6][8] = 1
M[8][10] = 1

print(M)

# Parámetros
num_ants = 15
#num_iterations = 100
alpha = 1.0          # Influencia de las feromonas
beta = 2.0           # Influencia de la heurística (inverso de la distancia)
evaporation_rate = 0.3
pheromone_deposit = 1.0

# Inicializamos la matriz de feromonas
pheromone_matrix = np.ones_like(M)

# Inicializamos la matriz de heurística (inverso de la distancia)
heuristic_matrix = 1 / (M)

# Función de aptitud (ditancia total de la ruta)
def route_distance(route):
    distance = 0
    for i in range(len(route) - 1):
        distance += M[route[i]][route[i + 1]]
    distance += M[route[-1]][route[0]]  # Regresar al punto inicial
    return distance

# Función para construir una ruta para una hormiga
def construct_route(start_city):
    route = [start_city]
    visited = set(route)

    for _ in range(9):  # 10 ciudades en total , ya se visitó la inicial
        current_city = route[-1]
        probabilities = []

        # Calcular probabilidades para las ciudades no visitadas
        for next_city in range(1, 11):
            if next_city not in visited:
                prob = (pheromone_matrix[current_city][next_city] ** alpha) * \
                       (heuristic_matrix[current_city][next_city] ** beta)
                probabilities.append((next_city, prob))

        # Normalizar y seleccionar aleatoriamente la ciudad siguiente
        total_prob = sum(prob for _, prob in probabilities)
        probabilities = [(city, prob / total_prob) for city, prob in probabilities]
        next_city = random.choices([city for city, _ in probabilities],
                                   weights=[prob for _, prob in probabilities])[0]

        route.append(next_city)
        visited.add(next_city)

    return route

# Funcion para actualizar las feromonas
def update_pheromones(best_route):
    global pheromone_matrix
    pheromone_matrix *= (1 - evaporation_rate)  # Evaporación de toda la matriz

    # Depósito de feromonas solo en la mejor ruta
    for i in range(len(best_route) - 1):
        city_a = best_route[i]
        city_b = best_route[i + 1]
        pheromone_matrix[city_a][city_b] += pheromone_deposit / route_distance(best_route)
        pheromone_matrix[city_b][city_a] += pheromone_deposit / route_distance(best_route)



def ACO(num_iterations):
    global best_route, best_distance,count
    for iteration in range(num_iterations):

        # Cada hormiga construye una ruta, con una ciudad de inicio aleatoria
        for ant in range(num_ants):
            start_city = random.randint(1, 10)
            route = construct_route(start_city)
            route_dist = route_distance(route)

            # Actualizamos la mejor ruta
            if route_dist < best_distance:
                best_distance = route_dist
                best_route = route

        # Actualizar feromonas en la mejor ruta
        update_pheromones(best_route)

        count += 1
        print(f" {count}: Best distance = {best_distance}, Best route = {best_route}")




#Definimos las variables para guardar la mejor ruta y distancia
best_route = None
best_distance = np.inf
count = 0
# Ejecutar el algoritmo
ACO(5)




[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 1. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 1. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 1. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 1. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 1.]
 [2. 2. 1. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]
 1: Best distance = 14.0, Best route = [7, 9, 10, 6, 8, 2, 4, 1, 3, 5]
 2: Best distance = 14.0, Best route = [7, 9, 10, 6, 8, 2, 4, 1, 3, 5]
 3: Best distance = 14.0, Best route = [7, 9, 10, 6, 8, 2, 4, 1, 3, 5]
 4: Best distance = 14.0, Best route = [7, 9, 10, 6, 8, 2, 4, 1, 3, 5]
 5: Best distance = 14.0, Best route = [7, 9, 10, 6, 8, 2, 4, 1, 3, 5]


In [14]:
ACO(10)

 6: Best distance = 13.0, Best route = [3, 5, 7, 9, 2, 4, 6, 1, 8, 10]
 7: Best distance = 13.0, Best route = [3, 5, 7, 9, 2, 4, 6, 1, 8, 10]
 8: Best distance = 13.0, Best route = [3, 5, 7, 9, 2, 4, 6, 1, 8, 10]
 9: Best distance = 11.0, Best route = [3, 5, 7, 9, 2, 4, 6, 8, 10, 1]
 10: Best distance = 11.0, Best route = [3, 5, 7, 9, 2, 4, 6, 8, 10, 1]
 11: Best distance = 11.0, Best route = [3, 5, 7, 9, 2, 4, 6, 8, 10, 1]
 12: Best distance = 11.0, Best route = [3, 5, 7, 9, 2, 4, 6, 8, 10, 1]
 13: Best distance = 11.0, Best route = [3, 5, 7, 9, 2, 4, 6, 8, 10, 1]
 14: Best distance = 11.0, Best route = [3, 5, 7, 9, 2, 4, 6, 8, 10, 1]
 15: Best distance = 11.0, Best route = [3, 5, 7, 9, 2, 4, 6, 8, 10, 1]
